import Foundation

struct Country: Identifiable, Sendable {
    let id: String
    let name: String
    let capital: String
    let flag: String
    let continent: String
    let landmark: String
}

enum Countries {
    static let all: [Country] = [
        Country(id: "fr", name: "France", capital: "Paris", flag: "🇫🇷", continent: "europa", landmark: "Eiffel Tower"),
        Country(id: "de", name: "Germany", capital: "Berlin", flag: "🇩🇪", continent: "europa", landmark: "Brandenburg Gate"),
        Country(id: "it", name: "Italy", capital: "Rome", flag: "🇮🇹", continent: "europa", landmark: "Colosseum"),
        Country(id: "es", name: "Spain", capital: "Madrid", flag: "🇪🇸", continent: "europa", landmark: "Sagrada Familia"),
        Country(id: "gb", name: "United Kingdom", capital: "London", flag: "🇬🇧", continent: "europa", landmark: "Big Ben"),
        Country(id: "pt", name: "Portugal", capital: "Lisbon", flag: "🇵🇹", continent: "europa", landmark: "Belém Tower"),
        Country(id: "nl", name: "Netherlands", capital: "Amsterdam", flag: "🇳🇱", continent: "europa", landmark: "Windmills"),
        Country(id: "be", name: "Belgium", capital: "Brussels", flag: "🇧🇪", continent: "europa", landmark: "Atomium"),
        Country(id: "ch", name: "Switzerland", capital: "Bern", flag: "🇨🇭", continent: "europa", landmark: "Matterhorn"),
        Country(id: "at", name: "Austria", capital: "Vienna", flag: "🇦🇹", continent: "europa", landmark: "Schönbrunn"),
        Country(id: "se", name: "Sweden", capital: "Stockholm", flag: "🇸🇪", continent: "europa", landmark: "Vasa Museum"),
        Country(id: "no", name: "Norway", capital: "Oslo", flag: "🇳🇴", continent: "europa", landmark: "Fjords"),
        Country(id: "dk", name: "Denmark", capital: "Copenhagen", flag: "🇩🇰", continent: "europa", landmark: "Little Mermaid"),
        Country(id: "fi", name: "Finland", capital: "Helsinki", flag: "🇫🇮", continent: "europa", landmark: "Northern Lights"),
        Country(id: "pl", name: "Poland", capital: "Warsaw", flag: "🇵🇱", continent: "europa", landmark: "Wawel Castle"),
        Country(id: "gr", name: "Greece", capital: "Athens", flag: "🇬🇷", continent: "europa", landmark: "Parthenon"),
        Country(id: "jp", name: "Japan", capital: "Tokyo", flag: "🇯🇵", continent: "terra", landmark: "Mount Fuji"),
        Country(id: "cn", name: "China", capital: "Beijing", flag: "🇨🇳", continent: "terra", landmark: "Great Wall"),
        Country(id: "kr", name: "South Korea", capital: "Seoul", flag: "🇰🇷", continent: "terra", landmark: "Gyeongbokgung"),
        Country(id: "in", name: "India", capital: "New Delhi", flag: "🇮🇳", continent: "terra", landmark: "Taj Mahal"),
        Country(id: "th", name: "Thailand", capital: "Bangkok", flag: "🇹🇭", continent: "terra", landmark: "Grand Palace"),
        Country(id: "vn", name: "Vietnam", capital: "Hanoi", flag: "🇻🇳", continent: "terra", landmark: "Ha Long Bay"),
        Country(id: "tr", name: "Türkiye", capital: "Ankara", flag: "🇹🇷", continent: "terra", landmark: "Hagia Sophia"),
        Country(id: "id", name: "Indonesia", capital: "Jakarta", flag: "🇮🇩", continent: "terra", landmark: "Borobudur"),
        Country(id: "sa", name: "Saudi Arabia", capital: "Riyadh", flag: "🇸🇦", continent: "terra", landmark: "Kaaba"),
        Country(id: "ae", name: "UAE", capital: "Abu Dhabi", flag: "🇦🇪", continent: "terra", landmark: "Burj Khalifa"),
        Country(id: "il", name: "Israel", capital: "Jerusalem", flag: "🇮🇱", continent: "terra", landmark: "Western Wall"),
        Country(id: "ph", name: "Philippines", capital: "Manila", flag: "🇵🇭", continent: "terra", landmark: "Chocolate Hills"),
        Country(id: "sg", name: "Singapore", capital: "Singapore", flag: "🇸🇬", continent: "terra", landmark: "Marina Bay"),
        Country(id: "my", name: "Malaysia", capital: "Kuala Lumpur", flag: "🇲🇾", continent: "terra", landmark: "Petronas Towers"),
        Country(id: "mn", name: "Mongolia", capital: "Ulaanbaatar", flag: "🇲🇳", continent: "terra", landmark: "Genghis Khan Statue"),
        Country(id: "np", name: "Nepal", capital: "Kathmandu", flag: "🇳🇵", continent: "terra", landmark: "Mount Everest"),
        Country(id: "eg", name: "Egypt", capital: "Cairo", flag: "🇪🇬", continent: "sahara", landmark: "Pyramids of Giza"),
        Country(id: "za", name: "South Africa", capital: "Pretoria", flag: "🇿🇦", continent: "sahara", landmark: "Table Mountain"),
        Country(id: "ke", name: "Kenya", capital: "Nairobi", flag: "🇰🇪", continent: "sahara", landmark: "Masai Mara"),
        Country(id: "ng", name: "Nigeria", capital: "Abuja", flag: "🇳🇬", continent: "sahara", landmark: "Zuma Rock"),
        Country(id: "ma", name: "Morocco", capital: "Rabat", flag: "🇲🇦", continent: "sahara", landmark: "Hassan II Mosque"),
        Country(id: "tz", name: "Tanzania", capital: "Dodoma", flag: "🇹🇿", continent: "sahara", landmark: "Kilimanjaro"),
        Country(id: "et", name: "Ethiopia", capital: "Addis Ababa", flag: "🇪🇹", continent: "sahara", landmark: "Lalibela"),
        Country(id: "gh", name: "Ghana", capital: "Accra", flag: "🇬🇭", continent: "sahara", landmark: "Cape Coast Castle"),
        Country(id: "tn", name: "Tunisia", capital: "Tunis", flag: "🇹🇳", continent: "sahara", landmark: "Carthage"),
        Country(id: "sn", name: "Senegal", capital: "Dakar", flag: "🇸🇳", continent: "sahara", landmark: "Gorée Island"),
        Country(id: "mg", name: "Madagascar", capital: "Antananarivo", flag: "🇲🇬", continent: "sahara", landmark: "Baobab Avenue"),
        Country(id: "rw", name: "Rwanda", capital: "Kigali", flag: "🇷🇼", continent: "sahara", landmark: "Volcanoes NP"),
        Country(id: "mu", name: "Mauritius", capital: "Port Louis", flag: "🇲🇺", continent: "sahara", landmark: "Le Morne"),
        Country(id: "ci", name: "Ivory Coast", capital: "Yamoussoukro", flag: "🇨🇮", continent: "sahara", landmark: "Basilica"),
        Country(id: "cm", name: "Cameroon", capital: "Yaoundé", flag: "🇨🇲", continent: "sahara", landmark: "Mount Cameroon"),
        Country(id: "dz", name: "Algeria", capital: "Algiers", flag: "🇩🇿", continent: "sahara", landmark: "Casbah"),
        Country(id: "us", name: "United States", capital: "Washington D.C.", flag: "🇺🇸", continent: "nova", landmark: "Statue of Liberty"),
        Country(id: "ca", name: "Canada", capital: "Ottawa", flag: "🇨🇦", continent: "nova", landmark: "Niagara Falls"),
        Country(id: "mx", name: "Mexico", capital: "Mexico City", flag: "🇲🇽", continent: "nova", landmark: "Chichén Itzá"),
        Country(id: "br", name: "Brazil", capital: "Brasília", flag: "🇧🇷", continent: "nova", landmark: "Christ Redeemer"),
        Country(id: "ar", name: "Argentina", capital: "Buenos Aires", flag: "🇦🇷", continent: "nova", landmark: "Iguazú Falls"),
        Country(id: "co", name: "Colombia", capital: "Bogotá", flag: "🇨🇴", continent: "nova", landmark: "Cartagena"),
        Country(id: "pe", name: "Peru", capital: "Lima", flag: "🇵🇪", continent: "nova", landmark: "Machu Picchu"),
        Country(id: "cl", name: "Chile", capital: "Santiago", flag: "🇨🇱", continent: "nova", landmark: "Easter Island"),
        Country(id: "cu", name: "Cuba", capital: "Havana", flag: "🇨🇺", continent: "nova", landmark: "Old Havana"),
        Country(id: "ec", name: "Ecuador", capital: "Quito", flag: "🇪🇨", continent: "nova", landmark: "Galápagos"),
        Country(id: "jm", name: "Jamaica", capital: "Kingston", flag: "🇯🇲", continent: "nova", landmark: "Blue Mountains"),
        Country(id: "cr", name: "Costa Rica", capital: "San José", flag: "🇨🇷", continent: "nova", landmark: "Arenal Volcano"),
        Country(id: "pa", name: "Panama", capital: "Panama City", flag: "🇵🇦", continent: "nova", landmark: "Panama Canal"),
        Country(id: "bo", name: "Bolivia", capital: "Sucre", flag: "🇧🇴", continent: "nova", landmark: "Salar de Uyuni"),
        Country(id: "uy", name: "Uruguay", capital: "Montevideo", flag: "🇺🇾", continent: "nova", landmark: "Punta del Este"),
        Country(id: "py", name: "Paraguay", capital: "Asunción", flag: "🇵🇾", continent: "nova", landmark: "Itaipu Dam"),
        Country(id: "au", name: "Australia", capital: "Canberra", flag: "🇦🇺", continent: "oceania", landmark: "Sydney Opera House"),
        Country(id: "nz", name: "New Zealand", capital: "Wellington", flag: "🇳🇿", continent: "oceania", landmark: "Milford Sound"),
        Country(id: "fj", name: "Fiji", capital: "Suva", flag: "🇫🇯", continent: "oceania", landmark: "Coral Reefs"),
        Country(id: "pg", name: "Papua New Guinea", capital: "Port Moresby", flag: "🇵🇬", continent: "oceania", landmark: "Highlands"),
        Country(id: "ws", name: "Samoa", capital: "Apia", flag: "🇼🇸", continent: "oceania", landmark: "To Sua Trench"),
        Country(id: "to", name: "Tonga", capital: "Nukuʻalofa", flag: "🇹🇴", continent: "oceania", landmark: "Royal Palace"),
        Country(id: "vu", name: "Vanuatu", capital: "Port Vila", flag: "🇻🇺", continent: "oceania", landmark: "Yasur Volcano"),
        Country(id: "pw", name: "Palau", capital: "Ngerulmud", flag: "🇵🇼", continent: "oceania", landmark: "Jellyfish Lake"),
        Country(id: "sb", name: "Solomon Islands", capital: "Honiara", flag: "🇸🇧", continent: "oceania", landmark: "Marovo Lagoon"),
        Country(id: "mh", name: "Marshall Islands", capital: "Majuro", flag: "🇲🇭", continent: "oceania", landmark: "Bikini Atoll"),
        Country(id: "fm", name: "Micronesia", capital: "Palikir", flag: "🇫🇲", continent: "oceania", landmark: "Nan Madol"),
        Country(id: "ki", name: "Kiribati", capital: "Tarawa", flag: "🇰🇮", continent: "oceania", landmark: "Christmas Island"),
        Country(id: "nr", name: "Nauru", capital: "Yaren", flag: "🇳🇷", continent: "oceania", landmark: "Buada Lagoon"),
        Country(id: "tv", name: "Tuvalu", capital: "Funafuti", flag: "🇹🇻", continent: "oceania", landmark: "Funafuti Atoll"),
        Country(id: "nc", name: "New Caledonia", capital: "Nouméa", flag: "🇳🇨", continent: "oceania", landmark: "Heart of Voh"),
    ]

    static func forContinent(_ id: String) -> [Country] { all.filter { $0.continent == id } }
}
